name: Run SPY Screener

on:
  schedule:
    # Every 30 minutes from 6:30 AM to 1:00 PM PST (14:30–21:00 UTC) on weekdays
    - cron: '*/30 14-20 * * 1-5'  # UTC time zone
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas ta rich matplotlib pillow requests

      - name: Run script
        run: python spy_itm_call_screener.py
