name: Run SPY Screener

on:
  schedule:
    - cron: '30 14 * * 1-5'  # 6:30 AM PST
    - cron: '0 16 * * 1-5'   # 8:00 AM PST
    - cron: '0 18 * * 1-5'   # 10:00 AM PST
    - cron: '0 20 * * 1-5'   # 12:00 PM PST
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas ta rich requests

      - name: Run script
        run: python spy_itm_call_screener.py


